/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import useColorStore from "../stores/colorStore";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/animatedSpeaker2.glb");
  const { actions } = useAnimations(animations, group);
  const colorStore = useColorStore();
  const colors = ["orange", "blue", "red", "purple", "green"];

  const materialKeys = Object.keys(materials);
  materialKeys.map((materialKey) => (materials[materialKey].skinning = true));

  useEffect(() => {
    const actionKeys = Object.keys(actions);
    actionKeys.map((actionKey) => actions[actionKey].play());
    group.current.position.x = -3;
    group.current.position.z = -9;
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        position={[0.02, 0, -0.02]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          name="Object_2"
          geometry={nodes.Object_2.geometry}
          material={materials.backplate}
        />
        <mesh
          name="Object_3"
          geometry={nodes.Object_3.geometry}
          material={materials.Wood_dark}
          material-color={"black"}
          position={[-0.09, 0, 0.01]}
        />
        <mesh
          name="Object_4"
          geometry={nodes.Object_4.geometry}
          material={nodes.Object_4.material}
          material-color={colors[colorStore.color]}
        />
        <mesh
          name="Object_5"
          geometry={nodes.Object_5.geometry}
          material={nodes.Object_5.material}
        />
        <mesh
          name="Object_6"
          geometry={nodes.Object_6.geometry}
          material={nodes.Object_6.material}
        />
        <mesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={nodes.Object_7.material}
        />
        <mesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={nodes.Object_8.material}
        />
        <mesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={nodes.Object_9.material}
        />
        <mesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={nodes.Object_10.material}
          material-color={"orange"}
        />
        <mesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={nodes.Object_11.material}
        />
        <mesh
          name="Object_12"
          geometry={nodes.Object_12.geometry}
          material={nodes.Object_12.material}
        />
        <mesh
          name="Object_13"
          geometry={nodes.Object_13.geometry}
          material={nodes.Object_13.material}
        />
        <mesh
          name="Object_14"
          geometry={nodes.Object_14.geometry}
          material={nodes.Object_14.material}
        />
        <mesh
          name="Object_15"
          geometry={nodes.Object_15.geometry}
          material={nodes.Object_15.material}
        />
        <mesh
          name="Object_16"
          geometry={nodes.Object_16.geometry}
          material={materials.metal_connect}
        />
        <mesh
          name="Object_17"
          geometry={nodes.Object_17.geometry}
          material={materials.ramka_czarna}
        />
        <mesh
          name="Object_18"
          geometry={nodes.Object_18.geometry}
          material={materials.red_plastic}
        />
        <mesh
          name="Object_19"
          geometry={nodes.Object_19.geometry}
          material={materials.white_plastic}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/animatedSpeaker.glb");
