/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/danceFloor.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
        <group position={[0, -402.8, 223.47]} rotation={[-1.57, 0, 0]}>
          <mesh geometry={nodes.Mesh_10.geometry} material={materials.material_18} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_11.geometry} material={materials.material_19} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_13.geometry} material={materials.material_20} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_14.geometry} material={materials.material_21} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_15.geometry} material={materials.material_22} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_16.geometry} material={materials.material_23} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_19.geometry} material={materials.material_26} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_21.geometry} material={materials.material_28} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_22.geometry} material={materials.material_29} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_24.geometry} material={materials.material_30} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_25.geometry} material={materials.material_31} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_26.geometry} material={materials.material_32} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_27.geometry} material={materials.material_33} position={[0, 23.05, 0.1]} />
          <mesh geometry={nodes.Mesh_32.geometry} material={nodes.Mesh_32.material} position={[0, 0.52, -125.07]} />
          <mesh
            geometry={nodes.Mesh_32001.geometry}
            material={nodes.Mesh_32001.material}
            position={[0.97, -0.17, 149.2]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/danceFloor.glb')
